services:
  - type: web
    name: OFERTA-ACADEMICA-CEDEPRO
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
